### ISSUE TITLE
eliminate errors in postfix logs

### ISSUE THREAD

**Issue by bbalazs-coder** [Glavic/Docker-postfix#1]
Hi!

In the postfix log I found "Untrusted TLS connection established to gmail-smtp" and "error: open database /etc/postfix/aliases.lmdb" messages. Please add these  command lines in the Dockerfile, to eliminate these! Thanks

newaliases					
apk update					
apk add ca-certificates
postconf -e 'smtp_tls_CAfile = /etc/ssl/certs/ca-certificates.crt'
postfix reload

**Comment by Glavic** [comment]
@bakaibalazs Thank you for your input. I have fixed this in commit https://github.com/Glavic/Docker-postfix/commit/7b6874d1296112ac3d74f216d39adfb26e284446 and https://github.com/Glavic/Docker-postfix/commit/0742659821384739fdb6563653f7e8e0896e4d5d
